### ISSUE TITLE
Bury new siblings of learning cards with separate intervals / exclude them

### ISSUE THREAD

**Issue by galantra** [rjgoif/anki-bury-future-sibs#1]
Thank you so much for making this public! I wonder if I can use it in a specific way. 
 
I have long learning steps that span over weeks ([this](https://eshapard.github.io/anki/anki-learning-steps-with-feedback.html) is the rationale). Now, the problem is that, if new siblings are issued on the same day, they will have exactly parallel learning steps until they progress from "learning" to "young". So, what I want to do is automatically bury learning siblings – learning siblings of today's seen new cards, while these are still in the learning state. 
What I want to avoid is burying new siblings on the day that their siblings are first seen – this would impede my learning.

For example, yesterday I saw two siblings for the first time: Kazakhstan – Nursultan and Nursultan – Kazakhstan. Both are still learning cards. Both are due today. Then today, I see the learning card Kazakhstan – Nursultan. I don't want to see the learning card Nursultan – Kazakhstan until tomorrow.

This will create sibling spacing for siblings that are both in the learning state but neither new nor young nor mature.

Additionally, I'd like to use the add-on just the way you described. With one additional feature: I'd need to postpone new card siblings of young and mature cards separately from new card siblings of learning cards. The reason for separation is that I want to use a different interval – something like 28 days for the first category, 1 day for the latter.

In my example, imagine I have a third sibling Point on Map – Nursultan. It's very old and I know it well. I see it during today's reviews. What I want is to bury both of its siblings until 28 days later.

In any case, I really want to avoid one thing: Burying new and learning siblings of a learning card for 28 days. This would be okay for vocabulary, but it's bad for the most important topics I learn because I have granular but thematically closely connected cloze notes. If it's not possible to bury siblings of learning cards separately, maybe it's possible to exclude them from burying altogether.

If it's not possible with your add-on, I'll try to figure out if I can do it with the add-on [Trigger and actions: change one card depending on what occurs on another card](https://ankiweb.net/shared/info/1981494159).

I see that this is a complicated idea, so please ask for any clarification needed.

Also, I read on reddit that you're porting your other add-ons. Take your time.

**Comment by rjgoif** [comment]
I think you want a few things that are fundamentally different from the motivations I had for writing this add-on in the first place. 

> what I want to do is automatically bury learning siblings

If I understand you correctly, you start with multiple siblings in the learning queue at the same time and you want to bury one when the other is due in that queue. Maybe it makes sense  for you to have multiple siblings in the learning queue because your queue can span 30 days, but I argue that you are creating a lot of interference (see #11 [here](https://www.supermemo.com/en/archives1990-2015/articles/20rules)) by having mutliple sibs in the queue together. Additionally, assuming both of the siblings mature without lapsing too much in the learning queue, they will be near each other in your learned card schedule going forward (unless you use a load balancer, which will probably separate them when intervals get really large).
I suggest preventing a new card from starting the learning process until its siblings have graduated. This can be done by setting the look-ahead interval to a day longer than your learning queue. I assume your initial learned interval is longer than the final step in your learning queue, so this should allow the new card in as soon as its sibling has graduated to learned. 
You can also fork my build into one that does a separate database query and buries learning queue cards (queues 1 and 3). I probably won't do it myself for the reason below

> I'd need to postpone new card siblings of young and mature cards separately from new card siblings of learning cards

This is doable, but I suspect that your use is pretty niche and I have a deadline to port my other 2.0 add-ons. You could fork my build and change the database search to only consider mature cards
Consider this line in my code:
`nidsDueToday = set(mw.col.db.list("select nid from cards where queue = 1 or (due <= ? and (queue=2 or queue = 3))", cutoff))`
Note that I treat cards in the learning queue (`cards where queue = 1`) in the same light as cards in the learned or day-learning queues 2 and 3. Just write a query that only looks at queue 2 (learned cards).
